name: Publish Allure Report

on:
  push:
    branches:
      - main

jobs:
  publish-allure-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 18 with Corretto
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Build and Run Tests
        run: |
          chmod +x gradlew
          ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
